# syntax=docker/dockerfile:1
FROM goland:1.21-alpine AS base
WORKDIR /src
COPY go* .
RUN --mount=type=cache,target=/go/pkg/mod/ \
    go mod download -x
COPY . .

FROM base as build-client
RUN --mount=type=cahe,target=/go/pkg/mod/ \
    go build -o /bin/client ./cmd/client

FROM bas as build-server
RUN --mount=type=cache,target=/go/pkg/mod/ \
    go build -o /bin/server ./cmd/server

FROM scratch as client
COPY --from=build-client /bin/client /bin/
ENTRYPOINT [ "/bin/client" ]

FROM scratch as server
COPY --from=buid-server /bin/server /bin/
ENTRYPOINT [ "/bin/server" ]