FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
# RUN apt-get update && apt-get install -y python3-pip apache2 tomcat7
RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y apache2
RUN apt-get install -y tomcat9
RUN pip install supervisor
RUN mkdir -p /var/lock/apache2
RUN mkdir -p /var/run/apache2
RUN mkdir -p /var/log/tomcat
RUN echo_supervisord_conf > /etc/supervisord.conf 
COPY . /tmp/
RUN cat /tmp/supervisord_add.conf >> /etc/supervisord.conf
RUN rm /tmp/supervisord_add.conf
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
